name: saborpty_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  animations: ^2.0.11
  awesome_snackbar_content: ^0.1.6
  cached_network_image: ^3.4.1
  firebase_auth: ^5.5.4
  firebase_core: ^3.13.1
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.8.0
  go_router: ^15.1.2 
  google_fonts: ^6.2.1
  google_sign_in: ^6.3.0
  http: ^1.4.0
  lottie: ^3.3.1
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true  
  
  assets:
    - assets/category/
    - assets/logo/
    - assets/lottie/