name: saborpty_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  animations: ^2.0.11
  awesome_snackbar_content: ^0.1.6
  cached_network_image: ^3.4.1
  firebase_auth: ^5.5.4
  firebase_core: ^3.13.1
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.6
  flutter_rating: ^2.0.2
  font_awesome_flutter: ^10.8.0
  go_router: ^15.1.2 
  google_fonts: ^6.2.1
  google_sign_in: ^6.3.0
  http: ^1.4.0
  intl: ^0.19.0
  introduction_screen: ^3.1.17
  lottie: ^3.3.1
  modal_bottom_sheet: ^3.0.0
  shared_preferences: ^2.3.0
  shimmer: ^3.0.0
  url_launcher: ^6.1.10
  youtube_player_iframe: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
flutter_native_splash:
  color: "#e56b2b"
  image: assets/logo/logotipe.png
  android_gravity: center
  ios_content_mode: center
  fullscreen: true
  android_12:
    image: assets/logo/logotipe.png
    icon_background_color: "#fd9f11"

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo/saborpty.png"
  adaptive_icon_background: "#e56b2b"
  adaptive_icon_foreground: "assets/logo/saborpty.png"

flutter:
  uses-material-design: true  
  
  assets:
    - assets/category/
    - assets/logo/
    - assets/lottie/